---
title: "Ethiopia Stochastic Frontiers Analysis Draft 1"
author: "Tomas Morley"
date: "31 januari 2017"
output: 
  word_document:
    reference_docx: ../Common/word_styles_01.docx
bibliography: ../Common/ETHYG.bib
---

```{r setup, include=FALSE}
# Knitr settings
library(rprojroot)
root <- find_root(is_rstudio_project)

library(knitr)
knitr::opts_chunk$set(
  fig.width=12, fig.height=8,
  dpi = 300,
  echo=FALSE, warning=FALSE, message=FALSE,
  fig.path = file.path(root,"FigTabMap/out-"),
  dev = "CairoPNG",
  dev.args = list(CairoPNG = list(bg = "transparent"))
  )

library(pander)
panderOptions('table.alignment.default', function(df)
    ifelse(sapply(df, is.numeric), 'right', 'left'))
panderOptions('table.split.table', Inf)
panderOptions('big.mark', ",")
panderOptions('keep.trailing.zeros', TRUE)
```

# Abstract



# Introduction

# Econometric methodology

## 1. Normal stochastic frontiers, all variables - Look at different model types only 2013 wave
## 2. Stochastic frontiers only 2013 looking at endogeneity - need to search for an instrument, prices might count, and then we can test for endogeneity.
## 3. Consider how we can add a panel to this - consider the missing data problem.
## 4. Look at spatial lags in just one year of the data

Try a panel of just those that fell into the panel correctly. And also add the 

# Data

The data come from the Ethiopia .... sample of ... rural households. One issue is that there was no 

Because both inputs are measured in per acre terms land is not included although we do include the overall landholdings recorded by the household as an additional measure of wealth.

We consider a stochastic frontiers model using data from the Ghana LSMS-ISA survey. Although part of a panel, we ignore the panel structure due to issues with collection for the second year of the panel. The dependent variable in our analysis is the log of maize yield measured in kilograms per hectare. We consider a large number of inputs which can be broken down into household level inputs, plot level inputs and spatial inputs at a low level of aggregation. 

# results

# Discussion


